apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: mayakshanesht/calculator
          stdin: true
          tty: true
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 30080  # Choose a port between 30000-32767
