apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-llm-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deepseek-llm
  template:
    metadata:
      labels:
        app: deepseek-llm
    spec:
      containers:
      - name: deepseek-llm-container
        image: mayakshanesht/llm-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-api-key
              key: api-key

---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-llm-service
spec:
  selector:
    app: deepseek-llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer