apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 5
  selector:
    matchLabels:
     app: calculator
  template:
    metadata:
     labels:
      app: calculator
    spec:
     containers:
      - name: calculator
          image: mayakshanesht/calculator
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: LoadBalancer
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    